<?php
include "connect.php";
$CREATE_OKREG="CREATE TABLE IF NOT EXISTS `okręgi`
 (`OkregID` INT NOT NULL AUTO_INCREMENT, 
 `Okreg` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`OkregID`)) 
  ENGINE = InnoDB;";
$conn->exec($CREATE_OKREG);

$CREATE_PLACOWKI= "CREATE TABLE IF NOT EXISTS `placówki` 
( `PlacowkiID` INT NOT NULL AUTO_INCREMENT, 
`Nazwa` VARCHAR(50) NOT NULL, 
`Ul` VARCHAR(50) NOT NULL, 
`Kod_Pocztowy` INT(5) NOT NULL, 
`Miasto` VARCHAR(50) NOT NULL, 
`Telefon` INT NOT NULL, 
`ID_OKRĘG` INT, 
PRIMARY KEY (`PlacowkiID`),
INDEX (`ID_OKRĘG`)) 
ENGINE = InnoDB;";
$conn->exec($CREATE_PLACOWKI);

$RELATION_PLACOWKI_OKREG = "ALTER TABLE `placówki` 
ADD FOREIGN KEY (`ID_OKRĘG`) 
REFERENCES `okręgi`(`OkregID`) 
ON DELETE CASCADE ON UPDATE CASCADE";
$conn->exec($RELATION_PLACOWKI_OKREG);

$CREATE_KLASA="CREATE TABLE IF NOT EXISTS `klasa` 
( `KlasaID` INT NOT NULL AUTO_INCREMENT, 
`Klasa` VARCHAR(50) NOT NULL,
`ID_PLACOWKI` INT, 
`ID_OKREG` INT, 
PRIMARY KEY (`KlasaID`), 
INDEX (`ID_PLACOWKI`), 
INDEX (`ID_OKREG`)) 
ENGINE = InnoDB";
$conn->exec($CREATE_KLASA);

$RELATION_KLASA_OKREG="ALTER TABLE `klasa` 
ADD FOREIGN KEY (`ID_OKREG`) 
REFERENCES `okręgi`(`OkregID`) 
ON DELETE CASCADE ON UPDATE CASCADE";
$conn->exec($RELATION_KLASA_OKREG);

$RELATION_KLASA_PLACOWKI="ALTER TABLE 
`klasa` ADD FOREIGN KEY (`ID_PLACOWKI`) 
REFERENCES `placówki`(`PlacowkiID`) 
ON DELETE CASCADE ON UPDATE CASCADE";
$conn->exec($RELATION_KLASA_PLACOWKI);

$CREATE_MEMBERS="CREATE TABLE IF NOT EXISTS `member`
(`MemberID` INT NOT NULL AUTO_INCREMENT,
`Imie` VARCHAR(30) NOT NULL,
`Nazwisko` VARCHAR(30) NOT NULL,
`Ul` VARCHAR(30) NOT NULL,
`Numer_Domu` VARCHAR(30) NOT NULL,
`Kod_Pocztowy` INT NOT NULL,
`Miasto` VARCHAR(30) NOT NULL,
`Nr_Tel_Rodzic_1` INT NOT NULL,
`Nr_Tel_Rodzic_2` INT NOT NULL,
`Status`  VARCHAR(30) NOT NULL,
`ID_KLASA` INT,
`ID_PLACOWKI` INT,
`ID_OKREG` INT,
PRIMARY KEY (`MemberID`),
INDEX (`ID_KLASA`),
INDEX (`ID_PLACOWKI`),
INDEX (`ID_OKREG`))
ENGINE= InnoDB";
$conn->exec($CREATE_MEMBERS);

$RELATION_MEMBER_OKREG = "ALTER TABLE `member`
ADD FOREIGN KEY (`ID_OKREG`)
REFERENCES `okręgi`(`OkregID`)
ON DELETE CASCADE ON UPDATE CASCADE";
$conn->exec($RELATION_MEMBER_OKREG);

$RELATION_MEMBER_PLACOWKI = "ALTER TABLE `member`
ADD FOREIGN KEY (`ID_PLACOWKI`)
REFERENCES `placówki`(`PlacowkiID`)
ON DELETE CASCADE ON UPDATE CASCADE";
$conn->exec($RELATION_MEMBER_PLACOWKI);


$RELATION_MEMBER_KLASA = "ALTER TABLE `member`
ADD FOREIGN KEY (`ID_KLASA`)
REFERENCES `klasa`(`KlasaID`)
ON DELETE CASCADE ON UPDATE CASCADE";
$conn->exec($RELATION_MEMBER_KLASA);

